### PR TITLE
fixes debug output for Vec

### LINKED ISSUE #11: Debug output of `Vec` shows tuple entries rather than `T`
Currently, the implementation of `fmt::Debug` is displaying the entries as tuples of `(index, value)`.

e.g.:
```rust
use std::fmt::Write as _;
let mut buf = String::new();
let v = vec![1, 2, 3];
write!(&mut buf, "{v:?}");
asssert_eq!(buf, "[1, 2, 3]");
```
```
assertion `left == right` failed
  left: "[(0, 1), (1, 2), (2, 3)]"
 right: "[1, 2, 3]"
```

### PR DESCRIPTION
**Pull request by chanced**
Resolves #11 by fixing debug output of Vec.

### CODE REVIEW

**Comment by clarfonthey** [comment]
Perhaps it would be better to implement what I mention in this comment: https://github.com/ibraheemdev/boxcar/issues/11#issuecomment-2350507051

Although gaps in the vec are likely to be rare, displaying them as an underscore (you can do `.entry(&format_args!("_"))` on `debug_list` to easily achieve this) might be better than just omitting them, since people will probably want to know that when debug-printing.

**Comment by chanced** [comment]
Ah, gotcha. I should have known that was intentional :)

Sorry about that. I'll close this and the PR.

**Comment by chanced** [comment]
re-opened incase you opt for it to resemble vec debug.

**Comment by ibraheemdev** [comment]
Would prefer some indication of the gaps but this is good for now. Thanks!

**Pull request merged**
