### PR TITLE
Avoid `AtomicU64` on unsupported platforms

### PR DESCRIPTION
**Pull request by ibraheemdev**
Resolves https://github.com/ibraheemdev/boxcar/issues/19.

### CODE REVIEW

**Comment by ibraheemdev** [comment]
@lscorcia can you confirm that this fixes your problem?

**Comment by lscorcia** [comment]
~/boxcar$ cargo test
   Compiling boxcar v0.2.7 (/home/homeassistant/boxcar)
error: this arithmetic operation will overflow
   --> src/raw.rs:611:31
    |
611 |         assert_eq!(max.entry, (1 << 63) - 1);
    |                               ^^^^^^^^^ attempt to shift left by `63_i32`, which would overflow
    |
    = note: `#[deny(arithmetic_overflow)]` on by default

error: could not compile `boxcar` due to previous error

**Comment by ibraheemdev** [comment]
That should fix it, do tests pass now? (Sorry I don't have a 32-bit machine to test this on)

**Comment by lscorcia** [comment]
No problem! All tests are green now! Thanks for your help!

```
$ cargo test
   Compiling boxcar v0.2.7 (/home/homeassistant/boxcar)
    Finished test [unoptimized + debuginfo] target(s) in 32.86s
     Running unittests src/lib.rs (target/debug/deps/boxcar-a04aa8ba1fbc0e49)

running 2 tests
test raw::tests::location ... ok
test raw::tests::max_entries ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running tests/vec.rs (target/debug/deps/vec-80eaf5fab974a14c)

running 3 tests
test clear ... ok
test simple ... ok
test stress ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

   Doc-tests boxcar

running 18 tests
test src/lib.rs - (line 15) ... ok
test src/lib.rs - (line 23) ... ok
test src/lib.rs - (line 53) ... ok
test src/lib.rs - Vec<T>::clear (line 305) ... ok
test src/lib.rs - Vec<T>::count (line 171) ... ok
test src/lib.rs - Vec<T>::get (line 203) ... ok
test src/lib.rs - Vec<T>::get_mut (line 216) ... ok
test src/lib.rs - Vec<T>::get_unchecked (line 238) ... ok
test src/lib.rs - Vec<T>::get_unchecked_mut (line 262) ... ok
test src/lib.rs - Vec<T>::is_empty (line 187) ... ok
test src/lib.rs - Vec<T>::iter (line 282) ... ok
test src/lib.rs - Vec<T>::new (line 74) ... ok
test src/lib.rs - Vec<T>::push (line 136) ... ok
test src/lib.rs - Vec<T>::push_with (line 152) ... ok
test src/lib.rs - Vec<T>::reserve (line 115) ... ok
test src/lib.rs - Vec<T>::with_capacity (line 90) ... ok
test src/lib.rs - vec (line 20) ... ok
test src/lib.rs - vec (line 29) ... ok

test result: ok. 18 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 110.03s

```

**Pull request merged**
